### ISSUE TITLE
Error in cpg_sites_matrix[x, , drop = F] : subscript out of bounds

### ISSUE THREAD

**Issue by vickyrev** [cgplab/PAMES#4]
When trying to run the sample data (to figure out how to run this with eRRBS data), I come accross this issue:
reduced <- reduce_to_islands(bs_control_toy_data, bs_toy_sites)
[2018-01-12 17:35:16] Reducing beta values...
Error in cpg_sites_matrix[x, , drop = F] : subscript out of bounds

> head(bs_control_toy_data)
           control_1 control_2 control_3 control_4 control_5 control_6
chr1_10470        NA        NA        NA        NA        NA        NA
chr1_10472        NA        NA        NA        NA        NA        NA
chr1_10485        NA        NA        NA        NA        NA        NA
chr1_10497      0.85      0.90      0.73      0.71      0.77      0.81
chr1_10525      0.91      0.92      0.95      0.93      0.95      0.84

> head(bs_toy_sites)
   chr   pos
1 chr1 10470
2 chr1 10472
3 chr1 10485
4 chr1 10497
5 chr1 10525

**Comment by romagnolid** [comment]
Right, that is a residual from a previous implementation of the function (didn't test it enough apparently): it included a step in which indexes of CpG sites located within the same island are collected. Now this step must be done separately thus allowing users to change the parameters and save different sets of indexes. I will provide a precomputed set for a quick test though. 
Sorry for the inconvenience.

**Comment by romagnolid** [comment]
Updated the examples, it should work now.

**Comment by vickyrev** [comment]
Still getting the same error. I want to test the code with some custom eRRBS data, so from the Details information: 
The two main functions of PAMES are ‘select_informative_sites’ (to
     retreive sites of interest), and ‘compute_purity’ (to compute
     purity of tumor samples providing a list of sites generated by
     ‘select_informative_sites’). **Additionally, if working with
     Bisulphite Sequencing data, users must first reduce the data with
     ‘reduce_to_islands’,** than select informative CpG islands with
     ‘select_informative_islands’, and finally estimate purity with
     ‘compute_purity’.

I wanted to start with reduce_to_islands function given that information. If you have any additional info that might help on how to use the pipeline from a standard eRRBS input, it would help a lot. Thx!

**Comment by romagnolid** [comment]
Can you check the package version? Just to be sure that the last version was installed correctly (should be version 0.2.1).

edit: 
I'm sorry, I noticed that an import step is missing from the Details:
before *running reduce_to_islands* you should first use *compute_island_indexes* providing a table reporting chromosome location and genomic coordinate of CpG sites from your experiment (see bs_toy_sites as an example). Then you must pass this list of indexes to *reduce_to_islands*. 
See the code below:

    indexes <- compute_island_indexes(cpg_location_table)
    reduce_matrix <- reduce_to_islands(data_matrix, indexes)

**Comment by vickyrev** [comment]
great! the first part (the indexing) works perfectly now, and I'm able to go forward a bit, now I'm getting a different error with the reduce_to_islands function (perhaps something else I might not be considering is missing?). I checked that the class of 'dat' is matrix. Indexes were calculated as you said in the previous message, with no errors.
The version of PAMES is indeed 0.2.1

> reduce_matrix <- reduce_to_islands(dat, indexes) 
[2018-01-17 11:39:18] Reducing beta values... 
[2018-01-17 11:39:18] Done 
Error in dimnames(x) <- dn :    
length of 'dimnames' [1] not equal to array extent

EDIT: it works! with the toy data and another dataset. It is an error derived from the structure of my own data, so I'll close this thread. Thx!
