### ISSUE TITLE
EPIC support

### ISSUE THREAD

**Issue by biobenkj** [cgplab/PAMES#5]
Thanks for writing this piece of software! I just used it and it's great. I built support for the EPIC platform in the select_informative_sites() function and was wondering if you'd be interested in a pull request?

It was built from the IlluminaHumanMethylationEPICanno.ilm10b2.hg19 annotations.

**Comment by romagnolid** [comment]
Hi, glad to hear that you appreciated our work! Sounds great, you can submit the pull request and I'll give it a look asap.
