### ISSUE TITLE
Subscript out of bounds in compute_purity()

### ISSUE THREAD

**Issue by GMFranceschini** [cgplab/PAMES#6]
When computing the reduced version of Beta tables for target region set (like in the BS case), if a specific region has no mapping probes at all in the original beta table, that region is discarded from the output. This might happen if a targetted assay does not cover at all some CGIs. In practice, this seems to cause `reduce_to_regions()` to generate outputs of different length, and this becomes a problem since `compute_purity()` uses indexes to retrieve the informative CGI. 

```
## part of compute_purity() function which can give some troubles: 

beta_values <- rbind(tumor_table[list_of_sites[["hyper"]], 
        ], max_purity - tumor_table[list_of_sites[["hypo"]], 
        ])

```

The workaround can be simple, like adding missing rows as `NA`, but we might want to fix this.
Alternatively, calling regions by CGI_id instead of index could be a solution as well.
Here a reproducible example. In case this makes sense to you let me know if I can help.

```

library(PAMES)
library(PAMESdata)

cgi_list = cpg_islands
sites = PAMES::bs_toy_sites
mat = PAMES::bs_toy_matrix
informative_cgi = PAMESdata::BRCA_islands

cgi_reduced = reduce_to_regions(beta_table = mat, cpg_sites = sites, cpg_regions = cgi_list, min_CpGs = 3)
dim(cgi_reduced)

compute_purity(cgi_reduced, informative_cgi)

##[2019-05-21 10:04:50] # Compute purity #
## Error in tumor_table[list_of_sites[["hyper"]], ] : 
##  subscript out of bounds
##
```

Best

**Comment by romagnolid** [comment]
Good catch :+1: 
Fixed with https://github.com/cgplab/PAMES/commit/98eee8009ecedfda6dfba1956229ba934509cb6d
