### ISSUE TITLE
Error: assert_that: length of assertion is not 1

### ISSUE THREAD

**Issue by LiyanJi-code** [cgplab/PAMES#8]
With the example data, error occurred as follows "Error: assert_that: length of assertion is not 1" when I run compute_purity(bs_tumor_toy_matrix, bs_toy_regions). 

And the bs_toy_regions give a result of
$hyper
integer(0)
$hypo
integer(0)

Please help me, thanks a lot.

**Comment by romagnolid** [comment]
Hello @LiyanJi571, I'll fix that asap.

**Comment by romagnolid** [comment]
Hello @LiyanJi571, I guess you took the example from the vignette. The example was just to show what commands to use, it was not supposed to produce meaningful results. Sorry, I understand that is quite misleading. 
Still, there was a bug in the function that I fixed.
Anyway if you need help for running the analysis please fell free to email me and I'll try to assist you.
