### ISSUE TITLE
IDAT files as input

### ISSUE THREAD

**Issue by MjelleLab** [cgplab/PAMES#9]
Hi, is there a vignette for the tool? I wonder how to convert idat-files and use it as input for the purity estimation. 

Best,

**Comment by romagnolid** [comment]
Hello @MjelleLab, thanks for your interest in our tool.

The worflow is briefly described in the package documentation `help(PAMES)`, but I plan to add a proper vignette soon. 
Regarding the idat-files, PAMES requires a matrix of beta values as input, so you'll need a different package to convert them: **minfi** is usually a good choice.
https://kasperdanielhansen.github.io/genbioconductor/html/minfi.html
